# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gzsync < Formula
  desc "gzsync command"
  homepage "https://github.com/kalyan02/gzsync"
  # version 0.1.3
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kalyan02/gzsync/releases/download/v0.1.3/gzsync_0.1.3_Darwin_x86_64.tar.gz"
      sha256 "0ea1abdd4891c899771b5c8bc3a4825fa612dc2ccbe3b65bb2b62690d6c7d073"
    end
    if Hardware::CPU.arm?
      url "https://github.com/kalyan02/gzsync/releases/download/v0.1.3/gzsync_0.1.3_Darwin_arm64.tar.gz"
      sha256 "be3039b2ec58995cae1c6d8524b0fee39fa327b77dd760a7c8d96499809f7b9e"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kalyan02/gzsync/releases/download/v0.1.3/gzsync_0.1.3_Linux_x86_64.tar.gz"
      sha256 "571c68bffc6e25a1fa410a662676f5117af339f8d08256299cf5e89cec9516b6"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kalyan02/gzsync/releases/download/v0.1.3/gzsync_0.1.3_Linux_arm64.tar.gz"
      sha256 "66b31d3e9133d99d0d67d7486bb56a98351e37a5bab79bc078de206a9a297b8a"
    end
  end

  def install
    bin.install "gzsync"
  end
end
